# Form implementation generated from reading ui file '.\frontend\pm_add_new_entry.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_add_new_entry(object):
    def setupUi(self, dialog_add_new_entry):
        dialog_add_new_entry.setObjectName("dialog_add_new_entry")
        dialog_add_new_entry.resize(600, 400)
        dialog_add_new_entry.setStyleSheet("QDialog {\n"
"background-color: #324D64;\n"
"}\n"
"\n"
"* {\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.widget_container = QtWidgets.QWidget(parent=dialog_add_new_entry)
        self.widget_container.setGeometry(QtCore.QRect(100, 80, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_submit_entry = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_submit_entry.setGeometry(QtCore.QRect(215, 185, 150, 30))
        self.btn_submit_entry.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_submit_entry.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_submit_entry.setObjectName("btn_submit_entry")
        self.input_service_name = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_service_name.setGeometry(QtCore.QRect(35, 30, 330, 30))
        self.input_service_name.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_service_name.setObjectName("input_service_name")
        self.input_login = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_login.setGeometry(QtCore.QRect(35, 75, 330, 30))
        self.input_login.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_login.setObjectName("input_login")
        self.input_password = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_password.setGeometry(QtCore.QRect(35, 120, 330, 30))
        self.input_password.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_password.setText("")
        self.input_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.input_password.setObjectName("input_password")
        self.btn_generate_password = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_generate_password.setGeometry(QtCore.QRect(35, 185, 150, 30))
        self.btn_generate_password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_generate_password.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_generate_password.setObjectName("btn_generate_password")
        self.feedback_label = QtWidgets.QLabel(parent=self.widget_container)
        self.feedback_label.setGeometry(QtCore.QRect(35, 160, 330, 16))
        self.feedback_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.feedback_label.setStyleSheet("QLabel {\n"
"color: #f54021;\n"
"font-size: 12px;\n"
"font-weight: light;\n"
"border: none;\n"
"}")
        self.feedback_label.setText("")
        self.feedback_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.feedback_label.setObjectName("feedback_label")
        self.btn_show = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_show.setGeometry(QtCore.QRect(310, 124, 25, 25))
        self.btn_show.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_show.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.btn_show.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/eye_open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/images/eye_closed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_show.setIcon(icon)
        self.btn_show.setCheckable(True)
        self.btn_show.setObjectName("btn_show")
        self.btn_copy = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_copy.setGeometry(QtCore.QRect(335, 123, 25, 25))
        self.btn_copy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_copy.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.btn_copy.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\frontend\\images/content_copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_copy.setIcon(icon1)
        self.btn_copy.setObjectName("btn_copy")
        self.btn_settings = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_settings.setGeometry(QtCore.QRect(7, 188, 25, 25))
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.btn_settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_settings.setIcon(icon2)
        self.btn_settings.setCheckable(True)
        self.btn_settings.setObjectName("btn_settings")
        self.key_image = QtWidgets.QLabel(parent=dialog_add_new_entry)
        self.key_image.setGeometry(QtCore.QRect(30, 30, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_add_new_entry)
        QtCore.QMetaObject.connectSlotsByName(dialog_add_new_entry)

    def retranslateUi(self, dialog_add_new_entry):
        _translate = QtCore.QCoreApplication.translate
        dialog_add_new_entry.setWindowTitle(_translate("dialog_add_new_entry", "Password Manager"))
        self.btn_submit_entry.setText(_translate("dialog_add_new_entry", "Подтвердить"))
        self.input_service_name.setPlaceholderText(_translate("dialog_add_new_entry", "Введите название сайта..."))
        self.input_login.setPlaceholderText(_translate("dialog_add_new_entry", "Введите логин..."))
        self.input_password.setPlaceholderText(_translate("dialog_add_new_entry", "Введите пароль..."))
        self.btn_generate_password.setText(_translate("dialog_add_new_entry", "Сгенерировать пароль"))
        self.key_image.setText(_translate("dialog_add_new_entry", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))
