# Form implementation generated from reading ui file '.\frontend\pm_add_new_entry.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import res_rc # Добавлено вручную


class Ui_dialog_add_new_entry(object):
    def setupUi(self, dialog_add_new_entry):
        dialog_add_new_entry.setObjectName("dialog_add_new_entry")
        dialog_add_new_entry.resize(600, 400)
        dialog_add_new_entry.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.widget_container = QtWidgets.QWidget(parent=dialog_add_new_entry)
        self.widget_container.setGeometry(QtCore.QRect(100, 80, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_submit_entry = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_submit_entry.setGeometry(QtCore.QRect(215, 180, 150, 30))
        self.btn_submit_entry.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_submit_entry.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_submit_entry.setObjectName("btn_submit_entry")
        self.input_service_name = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_service_name.setGeometry(QtCore.QRect(35, 35, 330, 30))
        self.input_service_name.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_service_name.setObjectName("input_service_name")
        self.input_login = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_login.setGeometry(QtCore.QRect(35, 80, 330, 30))
        self.input_login.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_login.setObjectName("input_login")
        self.input_password = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_password.setGeometry(QtCore.QRect(35, 125, 330, 30))
        self.input_password.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_password.setObjectName("input_password")
        self.btn_generate_password = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_generate_password.setGeometry(QtCore.QRect(35, 180, 150, 30))
        self.btn_generate_password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_generate_password.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_generate_password.setObjectName("btn_generate_password")
        self.key_image = QtWidgets.QLabel(parent=dialog_add_new_entry)
        self.key_image.setGeometry(QtCore.QRect(30, 30, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_add_new_entry)
        QtCore.QMetaObject.connectSlotsByName(dialog_add_new_entry)

    def retranslateUi(self, dialog_add_new_entry):
        _translate = QtCore.QCoreApplication.translate
        dialog_add_new_entry.setWindowTitle(_translate("dialog_add_new_entry", "Password Manager"))
        self.btn_submit_entry.setText(_translate("dialog_add_new_entry", "Создать"))
        self.input_service_name.setPlaceholderText(_translate("dialog_add_new_entry", "Введите название сайта..."))
        self.input_login.setPlaceholderText(_translate("dialog_add_new_entry", "Введите логин..."))
        self.input_password.setPlaceholderText(_translate("dialog_add_new_entry", "Введите пароль..."))
        self.btn_generate_password.setText(_translate("dialog_add_new_entry", "Сгенерировать пароль"))
        self.key_image.setText(_translate("dialog_add_new_entry", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_add_new_entry = QtWidgets.QDialog()
    ui = Ui_dialog_add_new_entry()
    ui.setupUi(dialog_add_new_entry)
    dialog_add_new_entry.show()
    sys.exit(app.exec())
