# Form implementation generated from reading ui file '.\frontend\pm_create_new_storage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import res_rc #Добавлено вручную


class Ui_dialog_create_new_storage(object):
    def setupUi(self, dialog_create_new_storage):
        dialog_create_new_storage.setObjectName("dialog_create_new_storage")
        dialog_create_new_storage.resize(600, 400)
        dialog_create_new_storage.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.widget_container = QtWidgets.QWidget(parent=dialog_create_new_storage)
        self.widget_container.setGeometry(QtCore.QRect(100, 80, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_submit_new_master_key = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_submit_new_master_key.setGeometry(QtCore.QRect(215, 165, 150, 30))
        self.btn_submit_new_master_key.setStyleSheet("background-color: #CDCDCD;")
        self.btn_submit_new_master_key.setObjectName("btn_submit_new_master_key")
        self.input_new_master_key = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_new_master_key.setGeometry(QtCore.QRect(35, 55, 330, 40))
        self.input_new_master_key.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_new_master_key.setObjectName("input_new_master_key")
        self.key_image = QtWidgets.QLabel(parent=dialog_create_new_storage)
        self.key_image.setGeometry(QtCore.QRect(30, 30, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_create_new_storage)
        QtCore.QMetaObject.connectSlotsByName(dialog_create_new_storage)

    def retranslateUi(self, dialog_create_new_storage):
        _translate = QtCore.QCoreApplication.translate
        dialog_create_new_storage.setWindowTitle(_translate("dialog_create_new_storage", "Password Manager"))
        self.btn_submit_new_master_key.setText(_translate("dialog_create_new_storage", "Создать"))
        self.input_new_master_key.setPlaceholderText(_translate("dialog_create_new_storage", "Придумайте мастер-пароль..."))
        self.key_image.setText(_translate("dialog_create_new_storage", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_create_new_storage = QtWidgets.QDialog()
    ui = Ui_dialog_create_new_storage()
    ui.setupUi(dialog_create_new_storage)
    dialog_create_new_storage.show()
    sys.exit(app.exec())
