# Form implementation generated from reading ui file '.\frontend\pm_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_login(object):
    def setupUi(self, dialog_login):
        dialog_login.setObjectName("dialog_login")
        dialog_login.resize(600, 400)
        dialog_login.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Segoe\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.widget_container = QtWidgets.QWidget(parent=dialog_login)
        self.widget_container.setGeometry(QtCore.QRect(100, 80, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_submit_master_key = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_submit_master_key.setGeometry(QtCore.QRect(215, 180, 150, 30))
        self.btn_submit_master_key.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_submit_master_key.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_submit_master_key.setObjectName("btn_submit_master_key")
        self.input_login = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_login.setGeometry(QtCore.QRect(35, 30, 330, 40))
        self.input_login.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_login.setClearButtonEnabled(True)
        self.input_login.setObjectName("input_login")
        self.label_feedback_login = QtWidgets.QLabel(parent=self.widget_container)
        self.label_feedback_login.setGeometry(QtCore.QRect(35, 70, 330, 16))
        self.label_feedback_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label_feedback_login.setStyleSheet("QLabel {\n"
"color: #f54021;\n"
"font-size: 12px;\n"
"font-weight: light;\n"
"border: none;\n"
"}\n"
"\n"
"QToolTip {\n"
"background-color: #CDCDCD;\n"
"border: none;\n"
"}")
        self.label_feedback_login.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_feedback_login.setText("")
        self.label_feedback_login.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_feedback_login.setObjectName("label_feedback_login")
        self.input_master_key = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_master_key.setGeometry(QtCore.QRect(35, 95, 330, 40))
        self.input_master_key.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_master_key.setClearButtonEnabled(True)
        self.input_master_key.setObjectName("input_master_key")
        self.label_feedback_master_key = QtWidgets.QLabel(parent=self.widget_container)
        self.label_feedback_master_key.setGeometry(QtCore.QRect(35, 135, 330, 16))
        self.label_feedback_master_key.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label_feedback_master_key.setToolTip("")
        self.label_feedback_master_key.setStyleSheet("QLabel {\n"
"color: #f54021;\n"
"font-size: 12px;\n"
"font-weight: light;\n"
"border: none;\n"
"}\n"
"\n"
"QToolTip {\n"
"background-color: #CDCDCD;\n"
"border: none;\n"
"}")
        self.label_feedback_master_key.setText("")
        self.label_feedback_master_key.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_feedback_master_key.setObjectName("label_feedback_master_key")
        self.key_image = QtWidgets.QLabel(parent=dialog_login)
        self.key_image.setGeometry(QtCore.QRect(30, 30, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_login)
        QtCore.QMetaObject.connectSlotsByName(dialog_login)

    def retranslateUi(self, dialog_login):
        _translate = QtCore.QCoreApplication.translate
        dialog_login.setWindowTitle(_translate("dialog_login", "Password Manager"))
        self.btn_submit_master_key.setText(_translate("dialog_login", "Войти"))
        self.input_login.setPlaceholderText(_translate("dialog_login", "Введите логин..."))
        self.input_master_key.setPlaceholderText(_translate("dialog_login", "Введите мастер-пароль..."))
        self.key_image.setText(_translate("dialog_login", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))
