# Form implementation generated from reading ui file 'frontend/pm_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(600, 700)
        main_window.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_container.setGeometry(QtCore.QRect(70, 80, 500, 600))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_add_new_entry = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_add_new_entry.setGeometry(QtCore.QRect(335, 550, 140, 30))
        self.btn_add_new_entry.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_new_entry.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_add_new_entry.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btn_add_new_entry.setStyleSheet("QPushButton {\n"
"background-color: #fff;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(255, 255, 255, 0.45);\n"
"}")
        self.btn_add_new_entry.setObjectName("btn_add_new_entry")
        self.table_entries = QtWidgets.QTableWidget(parent=self.widget_container)
        self.table_entries.setGeometry(QtCore.QRect(25, 25, 450, 510))
        self.table_entries.setMinimumSize(QtCore.QSize(450, 0))
        self.table_entries.setStyleSheet("QTableView {\n"
"background-color: #CDCDCD;\n"
"font-weight: normal;\n"
"}\n"
"\n"
"QTableView::section {\n"
"background-color: #fff;\n"
"height: 35px;\n"
"}\n"
"\n"
"QTableView::item {\n"
"border-style: none;\n"
"border-bottom: #9A9A9A;\n"
"width: 415px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"border: none;\n"
"background-color: rgba(50, 77, 100, 50);\n"
"}")
        self.table_entries.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.table_entries.setShowGrid(True)
        self.table_entries.setRowCount(0)
        self.table_entries.setColumnCount(4)
        self.table_entries.setObjectName("table_entries")
        item = QtWidgets.QTableWidgetItem()
        self.table_entries.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_entries.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_entries.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_entries.setHorizontalHeaderItem(3, item)
        self.table_entries.horizontalHeader().setDefaultSectionSize(112)
        self.table_entries.horizontalHeader().setSortIndicatorShown(False)
        self.table_entries.verticalHeader().setVisible(False)
        self.key_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.key_image.setGeometry(QtCore.QRect(0, 0, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Password Manager"))
        self.btn_add_new_entry.setText(_translate("main_window", "Добавить"))
        item = self.table_entries.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Сервис"))
        item = self.table_entries.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Логин"))
        item = self.table_entries.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Пароль"))
        item = self.table_entries.horizontalHeaderItem(3)
        item.setText(_translate("main_window", " "))
        self.key_image.setText(_translate("main_window", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))
