# Form implementation generated from reading ui file '.\frontend\pm_start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import res_rc # Добавлено вручную


class Ui_dialog_start(object):
    def setupUi(self, dialog_start):
        dialog_start.setObjectName("dialog_start")
        dialog_start.resize(600, 400)
        dialog_start.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.widget_container = QtWidgets.QWidget(parent=dialog_start)
        self.widget_container.setGeometry(QtCore.QRect(100, 80, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_login = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_login.setGeometry(QtCore.QRect(75, 55, 250, 40))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_login.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.btn_create_new_storage = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_create_new_storage.setGeometry(QtCore.QRect(75, 135, 250, 40))
        self.btn_create_new_storage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_create_new_storage.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_create_new_storage.setObjectName("btn_create_new_storage")
        self.key_image = QtWidgets.QLabel(parent=dialog_start)
        self.key_image.setGeometry(QtCore.QRect(30, 30, 100, 156))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_start)
        QtCore.QMetaObject.connectSlotsByName(dialog_start)

    def retranslateUi(self, dialog_start):
        _translate = QtCore.QCoreApplication.translate
        dialog_start.setWindowTitle(_translate("dialog_start", "Password Manager"))
        self.btn_login.setText(_translate("dialog_start", "Войти в Менеджер Паролей"))
        self.btn_create_new_storage.setText(_translate("dialog_start", "Создать новое хранилище"))
        self.key_image.setText(_translate("dialog_start", "<html><head/><body><p><img src=\":/key/images/key.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_start = QtWidgets.QDialog()
    ui = Ui_dialog_start()
    ui.setupUi(dialog_start)
    dialog_start.show()
    sys.exit(app.exec())
