# Form implementation generated from reading ui file 'frontend/pm_signup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_signup(object):
    def setupUi(self, dialog_signup):
        dialog_signup.setObjectName("dialog_signup")
        dialog_signup.resize(530, 350)
        dialog_signup.setStyleSheet("background-color: #324D64;\n"
"font: normal bold 12px/15px \'Inter\', sans-serif;\n"
"color: #000000;\n"
"\n"
"")
        self.widget_container = QtWidgets.QWidget(parent=dialog_signup)
        self.widget_container.setGeometry(QtCore.QRect(66, 55, 400, 240))
        self.widget_container.setStyleSheet("background-color: #747474;\n"
"border: 1px solid #000;\n"
"border-top-color: #fff;\n"
"border-left-color: #fff;\n"
"")
        self.widget_container.setObjectName("widget_container")
        self.btn_submit_new_master_key = QtWidgets.QPushButton(parent=self.widget_container)
        self.btn_submit_new_master_key.setGeometry(QtCore.QRect(215, 180, 150, 30))
        self.btn_submit_new_master_key.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_submit_new_master_key.setStyleSheet("QPushButton {\n"
"background-color: #CDCDCD;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(205, 205, 205, 0.4);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"background-color: rgba(205, 205, 205, 0.1);\n"
"}")
        self.btn_submit_new_master_key.setObjectName("btn_submit_new_master_key")
        self.input_new_master_key = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_new_master_key.setGeometry(QtCore.QRect(35, 95, 330, 40))
        self.input_new_master_key.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_new_master_key.setClearButtonEnabled(True)
        self.input_new_master_key.setObjectName("input_new_master_key")
        self.label_feedback_master_key = QtWidgets.QLabel(parent=self.widget_container)
        self.label_feedback_master_key.setGeometry(QtCore.QRect(35, 135, 330, 16))
        self.label_feedback_master_key.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label_feedback_master_key.setStyleSheet("QLabel {\n"
"color: #f54021;\n"
"font-size: 12px;\n"
"font-weight: light;\n"
"border: none;\n"
"}")
        self.label_feedback_master_key.setText("")
        self.label_feedback_master_key.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_feedback_master_key.setObjectName("label_feedback_master_key")
        self.input_new_login = QtWidgets.QLineEdit(parent=self.widget_container)
        self.input_new_login.setGeometry(QtCore.QRect(35, 30, 330, 40))
        self.input_new_login.setStyleSheet("QLineEdit {\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-style: italic;\n"
"}")
        self.input_new_login.setClearButtonEnabled(True)
        self.input_new_login.setObjectName("input_new_login")
        self.label_feedback_login = QtWidgets.QLabel(parent=self.widget_container)
        self.label_feedback_login.setGeometry(QtCore.QRect(35, 70, 330, 16))
        self.label_feedback_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label_feedback_login.setStyleSheet("QLabel {\n"
"color: #f54021;\n"
"font-size: 12px;\n"
"font-weight: light;\n"
"border: none;\n"
"}\n"
"\n"
"QToolTip {\n"
"background-color: #CDCDCD;\n"
"border: none;\n"
"}")
        self.label_feedback_login.setText("")
        self.label_feedback_login.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_feedback_login.setObjectName("label_feedback_login")
        self.key_image = QtWidgets.QLabel(parent=dialog_signup)
        self.key_image.setGeometry(QtCore.QRect(15, 18, 71, 111))
        self.key_image.setStyleSheet("background-color: none;\n"
"")
        self.key_image.setText("")
        self.key_image.setPixmap(QtGui.QPixmap(":/key/images/key.png"))
        self.key_image.setScaledContents(True)
        self.key_image.setObjectName("key_image")
        self.key_image.raise_()
        self.widget_container.raise_()

        self.retranslateUi(dialog_signup)
        QtCore.QMetaObject.connectSlotsByName(dialog_signup)

    def retranslateUi(self, dialog_signup):
        _translate = QtCore.QCoreApplication.translate
        dialog_signup.setWindowTitle(_translate("dialog_signup", "Password Manager"))
        self.btn_submit_new_master_key.setText(_translate("dialog_signup", "Создать"))
        self.input_new_master_key.setPlaceholderText(_translate("dialog_signup", "Придумайте мастер-пароль..."))
        self.input_new_login.setPlaceholderText(_translate("dialog_signup", "Придумайте логин..."))
