name: Testing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for Qt
      run: |
        sudo apt update
        sudo apt install -y \
          xvfb \
          libegl1 \
          libgl1-mesa-glx \
          libxcb-xinerama0 \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxcb-sync1 \
          libxcb-xfixes0 \
          libxcb-xkb1 \
          libxkbcommon-x11-0 \
          libxkbcommon0 \
          libxrender1 \
          libfontconfig1 \
          libdbus-1-3
    - name: Install dependencies
      run: pip install uv && make setup-dev
    - name: Run tests
      run: xvfb-run -a make test
