name: Publish test-coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies for Qt
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            xvfb \
            libegl1 \
            libgl1 \
            libxcb-xinerama0 \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-sync1 \
            libxcb-xfixes0 \
            libxcb-xkb1 \
            libxkbcommon-x11-0 \
            libxkbcommon0 \
            libxrender1 \
            libfontconfig1 \
            libdbus-1-3
      - name: Install packages
        run: pip install uv && make setup-dev
      - name: Run tests
        run: |
          export QT_DEBUG_PLUGINS=1
          export QT_XCB_GL_INTEGRATION=xcb_egl
          xvfb-run -a make test-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
